### PR TITLE
build: Respect MSVC runtime configuration

### PR DESCRIPTION
**Pull request by BurningEnlightenment**
Fixes ned14/llfio#123

### CODE REVIEW

**Comment by BurningEnlightenment** [comment]
Mmmh, I guess that might lead to specifying said flags twice. If someone fiddles with `CXX_STATIC_RUNTIME` it might lead to a mismatch. By default we parse `CMAKE_MSVC_RUNTIME_LIBRARY ` if it is set.
https://github.com/ned14/quickcpplib/blob/bb20eef1312ce49f5140da7bb709fd8d9bea1755/cmakelib/QuickCppLibSetupProject.cmake#L66-L70

Maybe it is time to retire `CXX_STATIC_RUNTIME`?

**Comment by ned14** [comment]
The ability to set different runtimes per target can be really useful. I wish cmake had it that way by default actually.

I'm trying to think of any way where if `CMP0091` is on and `CMAKE_MSVC_RUNTIME_LIBRARY` is set that anything breaks? We strip the cmake flags and set the property default so everything should work as before, `CMP0091` makes no difference to the main build. Only thing which doesn't work now and would now work would be the compiler probes. So I can't see anything but gain from merging this right?

**Comment by BurningEnlightenment** [comment]
> I wish cmake had it that way by default actually.

Sometimes our wishes are granted: There is [`MSVC_RUNTIME_LIBRARY`](https://cmake.org/cmake/help/latest/prop_tgt/MSVC_RUNTIME_LIBRARY.html) (initialized by `CMAKE_MSVC_RUNTIME_LIBRARY`) since CMake 3.15

> We strip the cmake flags and set the property default so everything should work as before, CMP0091 makes no difference to the main build. 

`CMAKE_MSVC_RUNTIME_LIBRARY`/`MSVC_RUNTIME_LIBRARY` work almost exactly like `CXX_STATIC_RUNTIME`, i.e. there is nothing which could be stripped from the global flag variables. This in turn means `-MD`/`-MT` get added twice or mismatched in the worst case.

**Comment by BurningEnlightenment** [comment]
@ned14 I'd like to follow up on `CXX_STATIC_RUNTIME`. It is currently only implemented for MSVC
https://github.com/ned14/quickcpplib/blob/877608af4558e7c2e3965f07575d0163c64e79ee/cmakelib/QuickCppLibSetupProject.cmake#L117
and has a built-in CMake replacement for the currently implemented MSVC case. Furthermore we don't use it in any of the public libraries. So I'd like to deprecate it and add an opt-out for defining said property.

**Pull request merged**
